version: '3.8'

services:
  kafka:
    image: apache/kafka:3.7.1
    container_name: kafka
    restart: always
    user: "root"
    environment:
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_NODE_ID=1
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      # 启用三类监听器
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      # 关键点：advertised listeners
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_HEAP_OPTS=-Xmx512m -Xms512m
    ports:
      - "9092:9092"  # 添加内部端口映射，供本地IDE使用
      - "9094:9094"  # 外部端口映射，供容器内服务使用
    volumes:
      - kafka_data:/tmp/kafka-logs
    networks:
      - app_net


  # 添加 stream 服务
  stream:
    build:
      context: ./stream
      dockerfile: Dockerfile
      args:
        http_proxy: http://172.26.48.1:7890
        https_proxy: http://172.26.48.1:7890
    depends_on:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - app_net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: always
    depends_on:
      - kafka
    environment:
      - KAFKA_CLUSTERS_0_NAME=kraft-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    ports:
      - "8081:8080"
    networks:
      - app_net

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=streamdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_net
      

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - postgres
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/streamdb
    ports:
      - "8086:8086"
    networks:
      - app_net

  collector-service:
    build:
      context: ./collector-service
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - postgres
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/streamdb
    ports:
      - "8085:8085"
    networks:
      - app_net

  alert-service:
    build:
      context: ./alert-service
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - postgres
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/streamdb
    ports:
      - "8084:8084"
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  kafka_data:
  postgres_data:

