# src/main/resources/application.yml
spring:
  application:
    name: stream-analyzer
  main:
    web-application-type: none
  kafka:
    bootstrap-servers: localhost:9094
    streams:
      application-id: stream-analyzer-app
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
        spring.json.trusted.packages: "*"
        num.stream.threads: 1
        state.dir: /tmp/kafka-streams