server:
  port: 8085

spring:
  application:
    name: collector-service
  main:
    web-application-type: none # 纯后台任务，不处理HTTP请求

  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      # 优化配置
      acks: 1
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      compression-type: snappy
    admin:
      fail-fast: true



# 日志配置
logging:
  level:
    org.springframework.kafka: INFO
    org.zewang.collector: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
